const Skills = [{name: 'cpp', percentage: 80 },
                  {name: 'JS', percentage: 70 },
                  {name: 'HTML & CSS', percentage: 70 },
                  {name: 'React', percentage: 60 },
                  {name: 'Linux', percentage: 60},
                  {name: 'Python', percentage: 60 },
                  {name: 'Excel', percentage: 60  },
                  {name: 'Java', percentage: 50},
                  {name: 'Kotlin', percentage: 60 },
                  {name: 'Express', percentage: 50 },
                  {name: 'C#', percentage: 50 },
                  {name: 'Jest', percentage: 50 },
                  {name: 'SQL', percentage: 50},
                ]
export default Skills